# Generated by Django 4.2.2 on 2023-06-19 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notestore',
            fields=[
                ('Note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'video')], max_length=100)),
                ('Note_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.note')),
            ],
        ),
    ]
